### ISSUE TITLE
ERROR in performing SVD on residuals

### ISSUE THREAD

**Issue by Scathacheng** [UcarLab/IA-SVA#9]
Hi there,
Sorry to bother you, I meet a problem when I perform the iasva function. I think the problem comes from the irlba function that in your package, and I don't know what should I do to fix it. Thanks a lot!
There is the error report:
IA-SVA running...

 Perform SVD on residuals
Warning in irlba(tresid - rowMeans(tresid), 1, tol = tol) :
  fast code path error starting vector near the null space; re-trying with fastpath=FALSE.
Error in irlba(tresid - rowMeans(tresid), 1, tol = tol) : 
  starting vector near the null space

**Comment by Scathacheng** [comment]
alright, I already figure it out. The problem was that I made a wrong mod. Thanks

**Comment by dleelab** [comment]
Hi Jiacheng,

Sorry for the late reply. I was out of town last week. If you have anything
else I can help you with, please let me know!

Best,
Don
